# Set the build language to NodeJS
language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

# command to run tests
script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
