# Set the build language to NodeJS
language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

install:
  - npm install -g codecov
  - npm i --save @fortawesome/free-solid-svg-icons
  - npm i --save @fortawesome/free-brands-svg-icons

# command to run tests
script:
  - npm test
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
